name: kubernetes-exec-helper
version: 0.1.0.0
library:
  source-dirs: src
dependencies:
  - base >=4.7 && <5.0
  - kubernetes == 0.1.0.0
  - kubeconfig
  - pem
  - x509
  - tls
  - x509-system
  - x509-store
  - data-default-class
  - connection
  - x509-validation
  - http-client >=0.5 && <0.6
  - http-client-tls
  - microlens >= 0.4.3 && <0.5
  - bytestring >=0.10.0 && <0.11
  - text >=0.11 && <1.3
  - safe-exceptions <0.2
  - network >= 2.6 && < 2.7
  - websockets >= 0.12 && < 0.13
  - hlint >= 2.0 && < 3.0
  - async
  - stm
  - mtl
  - HTTP >= 4000.3.9 && < 4000.3.12
  - optparse-applicative
  - process

executable : 
  main: Exec.hs
  source-dirs: examples
  dependencies: 
    - yaml
    - kubeconfig
    - kubernetes-exec-helper
    - process
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - yaml
      - kubeconfig
